# Generated by Django 3.2a1 on 2021-02-19 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='soap',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
