# Generated by Django 3.2a1 on 2021-02-19 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0002_soap_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soap',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_img/'),
        ),
    ]
